
pipelines:

  start-default: [ read-fs, import-deps ]
  end-default:  [ write-fs ]

  browsers: [ [ [firefox], [chrome] ] ]
  manifest: [ build-manifest ]
  default:  [ browsers, manifest ]
  beta:     [ beta-infer, default ]

  beta-watch: [ watch-fs, import-deps, beta ]

  beta-zip:     [ beta,                             write-zip ]
  release-zip:  [ default,                          write-zip ]
  beta-sign:    [ beta,    set-web-ext-updater-url, write-zip, write-fs, publish ]
  release-sign: [ default,                          write-zip, write-fs, publish ]


stages:
  read-fs:
    initial: true
    from: ./stages:read-fs
    options:
      from: .
      ignorefile: .gitignore
      ignore: |
        # (none)

  watch-fs:
    from: ./stages:watch-fs
    options:
      # inherits options fro `read-fs`, unless specified explicitly

  import-deps:
    from: ./stages:import-deps
    options:
      loaders: { }

  firefox:
    from: ./stages:set-state
    options:
      browser: firefox
  chrome:
    from: ./stages:set-state
    options:
      browser: chrome

  # calls `beta-set` with inferred `buildNumber`, if any
  beta-infer:
    from: ./stages:beta-infer
    options:
      force: # use this instead of inferring

  beta-set:
    from: ./stages:set-state
    options:
      buildNumber: null # mandatory
      versionInfix: b
      nameSuffix: ' - DEV'
      idSuffix: '-dev'

  m: build-manifest
  build-manifest:
    from: ./stages:build-manifest
    options:
      delete: [ ]
      set: { }

  set-web-ext-updater-url:
    from: ./stages:set-web-ext-updater-url

  w: write-fs
  write-fs:
    final: true
    from: ./stages:write-fs
    options:
      to: build
      name: null # default: browser
      clear: try
      linkFiles: false

  z: write-zip
  write-zip:
    final: true
    from: ./stages:write-zip
    options:
      to: build
      name: null # inferred from name, version, beta, and vendor/browser

  write-inplace:
    # writes/replaces `.generated` output files in-place to the repo
    final: true
    from: ./stages:write-fs
    options:
      to: src
      name: ''
      clear: false
      onlyGenerated: true
      linkFiles: true

  publish: push-store
  push-store:
    final: true
    from: ./stages:push-store
    options:
      saveTo:
      browser: null
      # ... credentials ...
